# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_postvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'UPVOTE'), (-1, 'DOWNVOTE')]),
        ),
    ]
