# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170910_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='vote',
            field=models.BooleanField(),
        ),
    ]
