# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170910_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'UPVOTE'), (0, 'NOVOTE'), (-1, 'DOWNVOTE')]),
        ),
    ]
