# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 04:16
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170910_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
