# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170911_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='vote_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='PostVote',
        ),
    ]
