# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20170911_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'UPVOTE'), (0, 'NOVOTE'), (-1, 'DOWNVOTE')])),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_likes',
        ),
        migrations.AddField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Post'),
        ),
        migrations.AddField(
            model_name='postvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
